### ISSUE TITLE
Social Login not enabled by Administrators.

### ISSUE THREAD

**Issue by shyr1punk** [mjimeyg/alternate-login#14]
Hello, thanks for this mod.

In the UCP tab Social Login i see "Social Login not enabled by Administrators."

I can link exists phpbb accounts with openID?

**Comment by mjimeyg** [comment]
You need to enable the options you want from the ACP.

You should be able to link existing accounts with OpenID.

**Comment by shyr1punk** [comment]
Firstly, sorry for my english.

Thank you, i decided the problem with UCP, when enabled FB login. When was enabled OpenID login only, i saw "Social Login not enabled by Administrators." message.

But i have new problem.

When logged in user on phpBB click openID provider button in UCP for link accounts, user logged off and after OpenID provider's page he redirected on forum registration page. Bud i think user dont be a log off.

I think redirecting code after line: if($user->data['user_id'] == ANONYMOUS)
But why user logging off?

Sorry, i hope you understand me.

**Comment by mjimeyg** [comment]
The UCP wouldn't be enabled with just OpenID as there aren't any options for OpenID so I wouldn't worry about that.

I think phpBB changed something in their session code as now phpBB doesn't automatically remember you were logged in after redirecting out of the site and back again.

Because of this I will have to remove OpenID linking,  I will be releasing an updated version to address this.

**Comment by shyr1punk** [comment]
Sorry, with session it's my problem. I copied forum at localhost, but dont setup new cookies domen. On production linking with account work
