### ISSUE TITLE
Facebook delink?

### ISSUE THREAD

**Issue by lcharette** [mjimeyg/alternate-login#8]
Another question here: I saw the lang key while translating the MOD, but couldn't find it on my setup. Is a link to remove the link between a Facebook account and phpBB in the User Control Panel? Is it something you're still working on it?

**Comment by mjimeyg** [comment]
I removed the feature as it made more sense to just let the user turn off syncing features.  

It's an older feature from when the mod had to create a password to log in due to a miss use of the functions available in phpbb.  Now the user can create their own password when they register or use the reset feature to change it.  The mod no longer alters the password unless the Quick Accounts are used and it needs a value for the password.

**Comment by mjimeyg** [comment]
I altered the install_mod.xml file to include you as a contributor, can you check to make sure that the way I have put it is ok with you?

**Comment by lcharette** [comment]
Yes it's ok, thanks!

**Comment by lcharette** [comment]
For the delink, it actually goes with issue #7. I'll update it first.

**Comment by lcharette** [comment]
I'll leave it like this for now. With #7, it's going to be fined. If users really want to delink their Facebook account (or other) I could probably create a one-click solution in the ACP or UCP or do it in phpMyAdmin.
